// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJmZ5b21xfx9-yEGuYh_QKXF3GP8KIw_Y',
    appId: '1:1003231592462:web:169a3254925dfefb8c3c5f',
    messagingSenderId: '1003231592462',
    projectId: 'secrypt-7ca69',
    authDomain: 'secrypt-7ca69.firebaseapp.com',
    storageBucket: 'secrypt-7ca69.firebasestorage.app',
    measurementId: 'G-KZ1PXRGY19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs2enGyEp7997MEDvzVd-wdYtEcyJ9o4c',
    appId: '1:1003231592462:android:6b85d18445a7017d8c3c5f',
    messagingSenderId: '1003231592462',
    projectId: 'secrypt-7ca69',
    storageBucket: 'secrypt-7ca69.firebasestorage.app',
  );
}
